title: "My DevOps Journey"
description: "Join me as I explore the vast world of DevOps, from automation tools to culture shifts. Dive into tutorials, insights, and stories from my personal experience."
email: george.natroshvili1996@gmail.com
github_username: GNatro
minimal_mistakes_skin: "neon"
search: true

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

permalink: /:categories/:title/
paginate: 5
paginate_path: "/page:num/"
timezone: "Asia/Tbilisi"

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "George Natroshvili"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "DevOps enthusiast. Sharing my journey and the lessons learned along the way."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:george.natroshvili1996@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/giorgi-natroshvili/"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:george.natroshvili1996@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/giorgi-natroshvili/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
